"""oauth identities

Links user_account rows to external Google/GitHub logins. Lookup is by
(provider, provider_user_id) — the provider's stable subject id — which the
unique constraint enforces; email is stored for reference only.

Revision ID: 1e045ac22050
Revises: 2c2b1694751f
Create Date: 2026-07-25 19:58:58.857039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e045ac22050'
down_revision: Union[str, None] = '2c2b1694751f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_identity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_identity_provider_user')
    )
    with op.batch_alter_table('oauth_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_identity_user_id'), ['user_id'], unique=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_identity_user_id'))

    op.drop_table('oauth_identity')
